# Jacoco Configuration
jacocoConfig.reports.csv.required=true
jacocoConfig.violationRules.rule.limit.minimum=0.8
jacoco.exclude.exception=**/*Exception*
jacoco.exclude.internal=[**/*$*,**/*GeneratedClass*]
