[versions]
junit5 = "5.10.0"
junit-platform = "1.10.0"

[libraries]
junit5-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[bundles]
#junit5 = ["junit5-api", "junit5-engine", "junit5-params", "junit5-platform-launcher"]
#junit = ["junit5-api", "junit5-engine", "junit5-params", "junit5-platform-launcher"]