/*********************************************************************************
**                                                                              **
**																				**
** Builds and publish  lsm-template.jar                 						**
**********************************************************************************/
/**                                                                             **
**   Template Project: no dependencies                                          **
**********************************************************************************/   

ext {
//	appName = 'template'
	println "ProjectName: " + project.name + 'appName: '+appName
}


dependencies {
//	implementation fileTree(dir: 'lib', include: '*.jar')
//	configurations.runtime.transitive = false
	implementation project(":Encryptor")
	implementation libs.bundles.google.guava
	implementation libs.bundles.jackson.databind
}
